# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    AppBundle\:
        resource: '../../src/AppBundle/*'

    exception.listener:
            class: AppBundle\EventListener\AuthenticationExceptionListener
            tags:
                - { name: kernel.event_listener, event: kernel.exception, method: onKernelException}

    a0_user_provider:
        class: AppBundle\Security\A0UserProvider
        arguments: ["@jwt_auth.auth0_service"]